BurntSushi/memchr

appveyor.yml, benches/bench.rs, src/lib.rs
This commit introduces the new function memrchr(), which is the reversed
counterpart to memchr(), and  it's corresponding testcases and benchmarks.
As discussed in #1. It looks live mingw [provides](https://github.com/dscho/msys/blob/master/msys/packages/coreutils/5.97/lib/memrchr.h) `memrchr()`, so a windows specific implementation is not necessary (not tested though, will check tomorrow). I am not really sure about other platforms though.
=> Implement safe interface to memrchr.

benches/bench.rs, src/lib.rs
There are patches in the pipeline for 16-bit pointer sizes and so on in the main rust tree, so that got me thinking about making sure it compiles no matter what the target pointer size is. Specialization is only for 32-bit and 64-bit platforms.
benchmark looks like this with the fallback used for memrchr, tested on 64-bit linux (fallback is normally not used in linux, but here it is).
```
test iterator          ... bench:      11,799 ns/iter (+/- 36) = 847 MB/s
test iterator_reversed ... bench:      11,781 ns/iter (+/- 29) = 848 MB/s
test libc_memchr       ... bench:         455 ns/iter (+/- 3) = 21978 MB/s
test libc_memrchr      ... bench:       2,236 ns/iter (+/- 12) = 4472 MB/s
```
=> Provide a faster fallback for memrchr

Cargo.toml, src/lib.rs
Follow up PR #3 with the same algorithm in forward search, manually implemented
memchr searching two usize at a time. This should be better than some libc implementations
on windows, so we enable this by default there.
I'm not very happy with the tangle of configuration conditions.
=> Provide faster memchr for windows

Cargo.toml, src/lib.rs
libc 0.2.4 includes memrchr (for linux, netbsd, openbsd). Reportedly the fallback is still better for the bsds.
=> Use memrchr definition from libc

src/lib.rs
The fallback implementation is not computing the aligned offset correctly(!). This is UB unfortunately and does crash on platforms where aligned accesses are not allowed.
@tomaka found a crash in memrchr on an ARMv7 (using the memrchr in libstd) and I suspect this was the cause. I wanted to put the fix here first, so that we can review it together. I think the original calculation was just bogus. See the first commit's log for more explanation.
=> Fix aligned access in memrchr fallback

.travis.yml, Cargo.toml, README.md, src/lib.rs
This still uses std by default, for compatibility with versions of Rust older than 1.6.0.  If compatibility with old versions is not a concern, this could be simplified to remove the optional feature and instead set `no_std` unconditionally.
=> Add optional no_std support

src/lib.rs
It's not possible for `Memchar.rposition > 0` so this branch is dead.
All tests pass.
=> Remove dead code

Cargo.toml, src/lib.rs
When compiling with `no_std` for systems with no C library we want to avoid linking to the `libc` crate. This PR makes `libc` an optional feature which is enabled by default.
=> Make linking to libc optional

src/lib.rs
The wasm32 target doesn't have a libc (it's empty), hence compile
memchr without libc for the wasm target.
=> Make it compile on wasm32

src/lib.rs
I intend to make the same PR for `src/libcore/slice/memchr.rs` in rust-lang/rust. If you are OK with this, I will r=you there.
=> fallback: fix variable name in docstrings

.travis.yml, Cargo.toml, appveyor.yml, ci/script.sh
This rolls up #25 and fixes CI such that tests are no longer run on Rust 1.12 (but we still check compilation).
=> rollup + fix ci

src/lib.rs
`self.haystack` here is already a reference, so no need to take
a reference to it.
=> clippy: Fix needless borrow warnings.

src/fallback.rs, src/lib.rs
This commit fixes a bug that caused undefined behavior by doing an
aligned read when an unaligned read was intended. In particular, we were
casting a `*const u8` to a `*const usize` and then reading its contents
to a `*mut usize`. The correct implementation is to reverse this such
that we read directly from `*const u8` and write to `*mut u8`, such that
ptr::copy_nonoverlapping knows to emit an unaligned load from the
`*const u8` pointer.
=> fallback: fix unaligned read

src/lib.rs
This is a duplicate of typo fixed in #40, the comment seems to also have
been a copy from the very similar method. See closed prematurely closed #41. :smile:
=> Fix duplicated typo

.travis.yml, ci/script.sh, src/tests/mod.rs
There is a hypothesis that the memchr rewrite from a while back is
getting things wrong on big endian, as shown here:
https://github.com/BurntSushi/ripgrep/issues/1144
As a result, we start testing in CI on a big endian architecture.
=> ci: test on big endian

bench/Cargo.lock, src/x86/avx.rs, src/x86/sse2.rs
Simplify `forward_pos[23]` / `reverse_pos[23]` by ORing masks.
I believe I am missing something because compared to all the SIMD optimizations it looks very simple. Anyway tests pass and benches show improvements so I wanted to share.
I got ~10-20% (up to 30%) speed ups on existing benches. Note that it is consistently slightly worse on the *never* tests, but the difference is small (1-2%) and on faster tests.
My machine is using AVX2, I am not sure for the other platform but I suppose it is ok.
<details><summary>memchr2/rust</summary>
```sh
memchr2/rust/huge/never time:   [18.858 us 18.954 us 19.117 us]
thrpt:  [28.984 GiB/s 29.232 GiB/s 29.381 GiB/s]
change:
time:   [-6.6607% -3.7235% -1.2840%] (p = 0.00 < 0.05)
thrpt:  [+1.3007% +3.8675% +7.1361%]
Performance has improved.
Found 12 …
```
=> Speed up multiple nibble searches

src/x86/avx.rs, src/x86/sse2.rs
In the sse2 and avx implementation of memchr3.
The memchr3 steps by two vector-sizes at time. When a match was found in
one of them, it would check the first one first, then the second one and
then the second one again.
It wasn't causing any incorrect behavior, but did extra work unless
compiler optimized it away.
=> simd: Remove redundant block in memchr3

src/x86/sse2.rs
I was very confused when I read this code because the bitshift amounts overlapped
so heavily and then are or-ed together. I believe the intention was to mean a number in bytes,
this changes it to a number in bits as bitshifts usually are.
=> Clarify bitshift amounts in sse2 pseudocode

src/lib.rs
Closes #51
Some reordering was introduced in `cfg` attributes to make it consistent
```rust
if a {
...
} else if all(b, c) {
...
} else if d {
...
} else {
...
}
```
becomes
```rust
#[cfg(a)]
...
#[cfg(all(
b,
c,
not(a),
))]
...
#[cfg(all(
d,
not(all(b, c, a)),
))]
...
#[cfg(all(
not(d),
not(all(b, c)),
not(a),
))]
...
```
It highlights which component of the conditional is important/introduced by putting them first
=> Support MIRI by using `naive` implementations

bench/Cargo.toml, bench/src/bench.rs, bench/src/imp.rs
I am trying to add aarch64 neon simd implementations (no promises though) and for that I need to compare it to the libc implementation which is already using neon instructions.
I removed the x86_64 guards in the benchmark code and it seems to be working fine.
=> Run libc benchmarks on non-x86_64 archs as well

.github/workflows/ci.yml, Cargo.toml
This commit adds the necessary `Cargo.toml` directives which enables
this crate to build with the standard library. This introduces some
optional off-by-deault dependencies which are only activated (and
overwritten) when built as part of the standard library.
=> Add metadata to build as a dep of libstd

.github/workflows/ci.yml, bench/src/memmem/imp.rs, build.rs, src/memmem/mod.rs, src/memmem/prefilter/mod.rs, src/memmem/prefilter/wasm.rs, src/memmem/vector.rs, src/memmem/wasm.rs
This commit adds simd acceleration support to the `memmem` module. This
is added with the freshly-stabilized support from rust-lang/rust#86204.
This mostly just cribs off the generic simd support for 128-bit types
built for sse, copying bits and pieces of code here and there. Some
refactoring happened internally to help reduce duplication where
possible.
I ran some initial benchmarks with the `memmem/krate/*` regex and a
hacked up single-threaded version of criterion. Some [initial
comparisons][compare] using Wasmtime as a runtime do indeed show a lot
of improvements, but there are indeed some slowdowns as well.
[compare]: https://gist.github.com/alexcrichton/6a72e682e7b6d505ade605359fbe3f2d
=> Add wasm simd support

bench/src/memmem/byterank.rs, bench/src/memmem/mod.rs, src/memmem/byterank/default.rs, src/memmem/byterank/mod.rs, src/memmem/mod.rs, src/memmem/prefilter/fallback.rs, src/memmem/prefilter/mod.rs, src/memmem/rarebytes.rs
This makes it possible for the caller to provide their own ranking function for individual bytes. This can potentially speed up searches if one has a better guess than the default for the frequency distribution of bytes in a particular haystack.
There is a lot of ceremony here, and it basically boils down to supporting this in no-std no-alloc configurations. I was tempted to just require alloc for this sort of thing and ask for something like `Arc<dyn Fn(u8) -> u8>`, but that would require some ceremony of its own internally to deal with in the no-alloc case. And forcing an allocation for every searcher construction that uses a customer ranker feels like bad juju to me.
Another choice would be to just ask for a `fn(u8) -> u8`, but this makes the case of "I analyzed a haystack at runtime …
=> memmem: add new HeuristicFrequencyRank

.github/workflows/ci.yml, Cargo.toml, src/cow.rs, src/lib.rs, src/memchr/x86/mod.rs, src/memmem/mod.rs, src/memmem/x86/avx.rs
This crate currently only has a 'std' feature and of course support for no-std. But in that mode, it was also no-alloc. In practice, this crate is virtually all core-only, that is, no-std and no-alloc. There are really only a few parts that want std or alloc. For std, runtime CPU feature detection requires it. For alloc, there are a few minor APIs that require allocation.
Previously, the only way to get the APIs that require allocation was to enable 'std'. This new feature permits getting those APIs without bringing in 'std'.
I don't expect this to unlock any new or interesting use cases, but it will make downstream configurations a little more sensible and less annoying.
Fixes #121
=> crate: add 'alloc' feature

README.md
The 2.6.0 release bumped the MSRV, but forgot to update the README to indicate that.
=> Update MSRV in `README.md`

README.md, fuzz/Cargo.lock, src/memmem/mod.rs, src/tests/mod.rs
This was an oversight in the 2.6 release. The forward case was marked as `alloc` (which was a new feature as of 2.6) but the reverse case was not.
=> use `alloc` instead of `std` for `FinderRev::into_owned`

src/lib.rs
This PR fixes a small typo. It should be `into_owned` instead of `into_ownedd` (additional `d`).
Thanks btw for creating and maintaining this crate!
Cheers
=> doc: fix a typo

.github/workflows/ci.yml, benchmarks/engines.toml, benchmarks/engines/libc/Cargo.toml, benchmarks/engines/rust-bytecount/Cargo.lock, benchmarks/engines/rust-bytecount/Cargo.toml, benchmarks/engines/rust-jetscii/Cargo.toml, benchmarks/engines/rust-memchr/Cargo.lock, benchmarks/engines/rust-memchr/Cargo.toml, benchmarks/engines/rust-memchrold/Cargo.toml, benchmarks/engines/rust-sliceslice/Cargo.lock, benchmarks/engines/rust-sliceslice/Cargo.toml, benchmarks/engines/rust-std/Cargo.toml, src/arch/all/mod.rs
This came from [@jhorstmann in #139][jhorstmann-is-equal]. It
simplifies `is_equal_raw` and also in turn simplifies its codegen.
Since this routine gets inlined into others, this winds up being a fair
improvement:
$ rebar diff -e memchr/memmem tmp/base.csv tmp/simpler-is-equal-raw.csv -t 1.1
benchmark                                          engine                       tmp/base.csv       tmp/simpler-is-equal-raw.csv
---------                                          ------                       ------------       ----------------------------
memmem/code/rust-library-never-fn-strength         rust/memchr/memmem/prebuilt  40.6 GB/s (1.24x)  50.2 GB/s (1.00x)
memmem/code/rust-library-never-fn-strength-paren   rust/memchr/memmem/prebuilt  39.4 GB/s (1.30x)  51.3 GB/s (1.00x) …
=> arch: simplify and improve is_equal_raw

.github/workflows/ci.yml, src/arch/mod.rs, src/arch/wasm32/memchr.rs, src/arch/wasm32/simd128/packedpair.rs, src/lib.rs, src/memchr.rs, src/memmem/searcher.rs, src/vector.rs
It turns out that providing routines with `#[target_feature(enable =
"simd128")]` on `wasm32` can fail in some older browsers. The specific
problem is not totally clear to me, but it is straight-forward enough
to fix (I hope) by just requiring that `simd128` be enabled at compile
time in order to include the `wasm32` SIMD modules in this crate.
This would not be a great solution if WASM supported runtime CPU
feature detection. And the status quo is that `simd128` has to be
enabled at compile time anyway for the SIMD code to take effect. So
this shouldn't cause any regressions and is likely something we can do
long term as well. We can re-evaluate once and if WASM gets support for
runtime CPU feature detection.
We also add a CI test for `wasm32` *without* the `simd128` target
feature …
=> require 'simd128' on 'wasm32'

src/arch/all/memchr.rs
Current generic ("all") implementation checks that a chunk (`usize`) contains a zero byte, and if it is, iterates over bytes of this chunk to find the index of zero byte. Instead, we can use more bit operations to find the index without loops.
Context: we use `memchr`, but many of our strings are short. Currently SIMD-optimized `memchr` processes bytes one by one when the string length is shorter than SIMD register. I suspect it can be made faster if we take `usize` bytes a chunk which does not fit into SIMD register and process it with such utility, similarly to how AVX2 implementation falls back to SSE2. So I looked at generic implementation to reuse it in SIMD-optimized version, but there were none. So here is it.
Suggestion how to check whether this PR makes it faster? In any case, it …
=> Faster memchr, memchr2 and memchr3 in generic version

.github/workflows/ci.yml, benchmarks/engines/rust-memchr/Cargo.lock, benchmarks/engines/rust-memchr/Cargo.toml, src/arch/all/memchr.rs
It turns out that #151 broke big endian targets and CI didn't catch it
because of a misconfiguration. (Namely, `cross` wasn't being used to
run tests even when it was being used to do builds.)
I spent about 15 minutes trying to fix this myself, but it quickly
became clear I'd need to spend more time writing out the bit arithmetic
to get it right.
cc @stepancheg - I'd be happy to take a new PR that fixes the
optimization for big endian targets.
Fixes #152
=> revert fallback memchr optimization

src/arch/aarch64/neon/packedpair.rs, src/vector.rs
I'm not completely aware how the code works, but I've tested this fix on aarch64_be. Previously, `memchr` produced many wrong results, but with this fix it's good.
aarch64 (little-endian) and other big-endian architectures should be unaffected.
This bugfix is necessary in order to build a working rustc, standard library and cargo.
=> Fix NEON optimization on big-endian aarch64
